[package]
name = "dino-tree"
version = "0.1.0"
authors = ["Florian Merz <fmerz@mozilla.com>"]

[dependencies]
serde_json = "1.0.24"
serde = "1.0.70"
serde_derive = "1.0.70"
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"