[package]
name = "dino-tree"
version = "0.1.0"
authors = ["Florian Merz <fmerz@mozilla.com>"]

[dependencies]
serde_json = "1.0.30"
serde = "1.0.79"
serde_derive = "1.0.79"
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rocket_contrib = "0.3.16"
lazy_static = "1.1"