---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: mozillaparsys/{{ .Values.name }}:{{ .Values.rev }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1Gi
          ports:
            - containerPort: 8888
          env:
            - name: DUMMY_TIMESTAMP
              value: "{{ now.Unix }}"
            - name: ELASTIC_HOST
              value: "{{ .Values.elastic_host }}"